---
title: "visualization"
author: "Xinyao WU"
date: "2018/9/27"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)
library(rnoaa)
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```




scatter_plot
```{r}
ggplot(weather_df,aes(x = tmin, y = tmax)) +
   geom_point(aes(color = name))
```

##MORE ggplot options

add a geom

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax)) +
   geom_point(aes(color = name))+
  geom_smooth()
```

add some options
```{r}
ggplot(weather_df,aes(x = tmin, y = tmax)) +
   geom_point(aes(color = name),alpha =0.4)+
  geom_smooth(se = FALSE)

```

add some options 
```{r}
ggplot(weather_df,aes(x = tmin, y = tmax, color=name)) +
   geom_point(alpha=0.4)+
  geom_smooth(se = FALSE)
```










```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x=tmin,y=tmax))+geom_point()
```







```{r}

```




